name: Build and publish


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install Node dependencies
      working-directory: ./XiePinyin
      run: npm ci
    - name: Run Gulp
      working-directory: ./XiePinyin
      run: gulp
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: File system publish
      run: dotnet publish -o ./_dist -c Release --self-contained false -r linux-x64
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: _dist
        path: _dist
        retention-days: 2

