name: Build and publish


on:
  push:
    branches: [ master ]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          
  build:
    runs-on: ubuntu-latest
    needs: [create_release]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install Node dependencies
      working-directory: ./XiePinyin
      run: npm ci
    - name: Run Gulp
      working-directory: ./XiePinyin
      run: gulp
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: File system publish
      run: dotnet publish -o ./_dist -c Release --self-contained false -r linux-x64
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: _dist
        path: _dist
        retention-days: 2
    - name: Upload artifacts to release
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: '_dist'
